# Generated by Django 3.0.6 on 2021-01-26 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=150)),
                ('cat_slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcat_name', models.CharField(max_length=150)),
                ('subcat_slug', models.SlugField(unique=True)),
                ('subcat_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=150)),
                ('pro_slug', models.SlugField(unique=True)),
                ('pro_description', models.TextField()),
                ('pro_price', models.FloatField()),
                ('pro_quantity', models.IntegerField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('pro_img1', models.ImageField(upload_to='')),
                ('pro_img2', models.ImageField(upload_to='')),
                ('pro_img3', models.ImageField(upload_to='')),
                ('pro_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Category')),
                ('pro_sub_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.SubCategory')),
            ],
            options={
                'ordering': ['-timeStamp'],
            },
        ),
    ]
