# Generated by Django 3.0.6 on 2021-01-26 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_first_name', models.CharField(max_length=150)),
                ('o_last_name', models.CharField(max_length=150)),
                ('o_city', models.CharField(max_length=150)),
                ('o_country', models.CharField(max_length=150)),
                ('o_total_charges', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oi_quantity', models.IntegerField()),
                ('oi_price', models.FloatField()),
                ('oi_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Product')),
            ],
        ),
    ]
