# Generated by Django 3.0.6 on 2021-01-26 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_order_orderitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
    ]
