# Generated by Django 3.0.6 on 2021-01-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210126_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='o_zip_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
