# Generated by Django 3.0.6 on 2021-01-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_product_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sub_cat',
            new_name='subcategory',
        ),
    ]
