# Generated by Django 3.0.6 on 2021-01-27 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210127_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cat',
            new_name='category',
        ),
    ]
